INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'caloi.png', 'CALOI', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'sense.png', 'SENSE', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'oggi.png', 'OGGI', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'gts.png', 'GTS', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'soul-cycles.png', 'SOUL CYCLES', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'ksw.png', 'KSW', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'tsw.png', 'TSW', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'audax.png', 'AUDAX', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'mormaii.png', 'MORMAII', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'monark.png', 'MONARK', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'south-bike.png', 'SOUTH BIKE', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'specialized.png', 'SPECIALIZED', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'cannondale.png', 'CANNONDALE', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'trek.png', 'TREK', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'scott.png', 'SCOTT', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'giant.png', 'GIANT', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'merida.png', 'MERIDA', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'santa-cruz.png', 'SANTA CRUZ', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'cervelo.png', 'CERVÉLO', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'focu.png', 'FOCU', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'kona.png', 'KONA', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'bmc.png', 'BMC', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'bianchi.png', 'BIANCHI', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'pinarello.png', 'PINARELLO', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'gt.png', 'GT', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (1, 'outra', 'Outra', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'ajp.png', 'AJP', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'aprilia.png', 'Aprilia', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'arc.png', 'Arc', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'arch-motorcycle.png', 'Arch Motorcycle', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'bajaj-auto.png', 'Bajaj Auto', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'benelli.png', 'Benelli', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'bimota.png', 'Bimota', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'bmw-motorrad.png', 'BMW Motorrad', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'brough-superior.png', 'Brough Superior', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'brutus.png', 'Brutus', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'buell.png', 'Buell', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'cagiva.png', 'Cagiva', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'ccm-motorcycles.png', 'CCM Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'ccw-cleveland-cycleWerks.png', 'CCW (Cleveland CycleWerks)', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'cfmoto.png', 'CFMoto', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'confederate-motorcycles.png', 'Confederate Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'curtiss-motorcycles.png', 'Curtiss Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'derbi.png', 'Derbi', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'ducati.png', 'Ducati', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'energica.png', 'Energica', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'erik-buell-racing.png', 'Erik Buell Racing (EBR)', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'evoke-motorcycles.png', 'Evoke Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'fantic-motor.png', 'Fantic Motor', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'fb-mondial.png', 'FB Mondial', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'fgr-midalu.png', 'FGR Midalu', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'gas-gas.png', 'Gas Gas', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'ghezzi-brian.png', 'Ghezzi-Brian', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'greeves-motorcycles.png', 'Greeves Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'haojue.png', 'Haojue', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'harley-davidson.png', 'Harley-Davidson', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'hesketh-motorcycles.png', 'Hesketh Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'honda.png', 'Honda', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'husqvarna.png', 'Husqvarna', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'hyosung.png', 'Hyosung', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'indian-motorcycle.png', 'Indian Motorcycle', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'kawasaki.png', 'Kawasaki', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'keeway.png', 'Keeway', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'ktm.png', 'KTM', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'lightning-motorcycles.png', 'Lightning Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'lito.png', 'Lito', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'macbor.png', 'Macbor', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'mash.png', 'Mash', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'matchless.png', 'Matchless', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'midual.png', 'Midual', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'montesa.png', 'Montesa', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'moto-guzzi.png', 'Moto Guzzi', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'moto-morini.png', 'Moto Morini', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'motus.png', 'Motus', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'mv-agusta.png', 'MV Agusta', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'norton.png', 'Norton', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'norton-motorcycles.png', 'Norton Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'orcal.png', 'Orcal', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'paton.png', 'Paton', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'peugeot-motocycles.png', 'Peugeot Motocycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'piaggio.png', 'Piaggio', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'royal-enfield.png', 'Royal Enfield', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'saietta.png', 'Saietta', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'saroléa.png', 'Saroléa', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'sherco.png', 'Sherco', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'skyteam.png', 'Skyteam', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'suzuki.png', 'Suzuki', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'swm-motorcycles.png', 'SWM Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'sw-motech.png', 'SW-MOTECH', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'sym.png', 'SYM', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'tarform.png', 'Tarform', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'tgb.png', 'TGB', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'triumph.png', 'Triumph', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'um-motorcycles.png', 'UM Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'vespa.png', 'Vespa', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'victory-motorcycles.png', 'Victory Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'vins-motors.png', 'Vins Motors', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'voge.png', 'Voge', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'vor-motori.png', 'Vor Motori', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'voxan.png', 'Voxan', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'vyrus.png', 'Vyrus', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'yamaha.png', 'Yamaha', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'yamaha-motor-corporation.png', 'Yamaha Motor Corporation', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'zero-motorcycles.png', 'Zero Motorcycles', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'zongshen.png', 'Zongshen', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (2, 'outra.png', 'Outra', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'abarth.png', 'Abarth', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'acura.png', 'Acura', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'acura.png', 'Acura', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'alpine.png', 'Alpine', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'ariel.png', 'Ariel', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'aston-martin.png', 'Aston Martin', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'audi.png', 'Audi', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'bentley.png', 'Bentley', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'bmw.png', 'BMW', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'borgward.png', 'Borgward', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'brilliance.png', 'Brilliance', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'bugatti.png', 'Bugatti', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'buick.png', 'Buick', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'byd.png', 'BYD', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'cadillac.png', 'Cadillac', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'chery.png', 'Chery', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'chevrolet.png', 'Chevrolet', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'chrysler.png', 'Chrysler', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'citroen.png', 'Citroën', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'dacia.png', 'Dacia', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'daewoo.png', 'Daewoo', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'daihatsu.png', 'Daihatsu', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'datsun.png', 'Datsun', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'dfsk.png', 'DFSK', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'dodge.png', 'Dodge', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'dongfeng.png', 'Dongfeng', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'faw.png', 'FAW', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'ferrari.png', 'Ferrari', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'fiat.png', 'Fiat', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'ford.png', 'Ford', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'geely.png', 'Geely', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'genesis.png', 'Genesis', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'gmc.png', 'GMC', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'great-wall.png', 'Great Wall', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'haval.png', 'Haval', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'holden.png', 'Holden', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'honda.png', 'Honda', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'hyundai.png', 'Hyundai', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'infiniti.png', 'Infiniti', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'isuzu.png', 'Isuzu', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'jac.png', 'JAC', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'jaguar.png', 'Jaguar', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'jeep.png', 'Jeep', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'kia.png', 'Kia', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'lada.png', 'Lada', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'lamborghini.png', 'Lamborghini', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'land-rover.png', 'Land Rover', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'lexus.png', 'Lexus', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'lincoln.png', 'Lincoln', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'mahindra.png', 'Mahindra', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'maruti-suzuki.png', 'Maruti Suzuki', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'maserati.png', 'Maserati', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'mazda.png', 'Mazda', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'mcLaren.png', 'McLaren', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'mercedes-benz.png', 'Mercedes-Benz', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'mini.png', 'MINI', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'mitsubishi.png', 'Mitsubishi', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'nissan.png', 'Nissan', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'pagani.png', 'Pagani', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'perodua.png', 'Perodua', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'peugeot.png', 'Peugeot', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'porsche.png', 'Porsche', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'proton.png', 'Proton', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'ram.png', 'RAM', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'renault.png', 'Renault', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'rolls-royce.png', 'Rolls-Royce', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'saab.png', 'Saab', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'seat.png', 'SEAT', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'skoda.png', 'Skoda', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'ssangyong.png', 'Ssangyong', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'subaru.png', 'Subaru', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'suzuki.png', 'Suzuki', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'tata.png', 'Tata', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'tesla.png', 'Tesla', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'toyota.png', 'Toyota', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'uaz.png', 'UAZ', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'vaz-lada.png', 'VAZ (Lada)', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'volkswagen.png', 'Volkswagen', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'volvo.png', 'Volvo', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'zotye.png', 'Zotye', now(), now());
INSERT INTO brands (vehicles_type_id, icon, name, created_at, updated_at ) VALUES (3, 'other.png', 'Outra', now(), now());
