CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	roles_id INT NOT NULL,
	full_name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	cpf VARCHAR(14) NULL,
	password VARCHAR(100) NULL,
	birth DATE NULL,
	phone VARCHAR(15) NULL,
	created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
	PRIMARY KEY (id),
	UNIQUE KEY unq_users_cpf (cpf),
	UNIQUE KEY unq_users_email (email),
	CONSTRAINT fk_users_roles FOREIGN KEY (roles_id) REFERENCES roles (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
